### ISSUE TITLE
统计可以存储吗？

### ISSUE THREAD

**Issue by whd120130** [wujiuye/qps-helper#1]
麻烦问一下就是统计请求次数，这个可以存储起来吗？

**Comment by wujiuye** [comment]
您好，这个目前不支持存储哦。感谢您的提问，有时间我再添加这个功能



---原始邮件---
发件人: "王慧东"<notifications@github.com&gt;
发送时间: 2020年7月20日(周一) 下午3:59
收件人: "wujiuye/qps-helper"<qps-helper@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [wujiuye/qps-helper] 统计可以存储吗？ (#1)




 
麻烦问一下就是统计请求次数，这个可以存储起来吗？

**Comment by wujiuye** [comment]
1.1.2-RELEASE版本已支持文件持久化资源指标数据统计
