### ISSUE TITLE
最小请求耗时统计有误

### ISSUE THREAD

**Issue by kikoskyblue** [wujiuye/qps-helper#11]
![截屏2023-12-11 10 37 27](https://github.com/wujiuye/qps-helper/assets/12949774/7489b687-b838-44ee-83b7-db17bd4721a9)

当没有统计数据时，直接输出统计信息时，最小请求耗时是2147483647

1.1.2-RELEASE

**Comment by wujiuye** [comment]
你好，这个问题已经在1.1.3-RELEASE修复了，可以看看这个ISSUE ==> https://github.com/wujiuye/qps-helper/issues/5
