### ISSUE TITLE
Flower#minRt 出现 Integer 最大值 2147483647

### ISSUE THREAD

**Issue by magestacks** [wujiuye/qps-helper#5]
大佬好，使用 `Flower#minRt` 方法会出现 Integer 最大值情况，麻烦看下，感谢。

按照分钟级别进行流量统计。

```java
new FlowHelper(FlowType.Minute);
```

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/77398366/204085365-6cc42af4-3349-4b09-bb50-9ec5bbebe04b.png">

<img width="855" alt="image" src="https://user-images.githubusercontent.com/77398366/204085385-a4aa9bd6-aa0f-4e6e-b5fc-c997e1cfcaa1.png">

**Comment by wujiuye** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by magestacks** [comment]
通过 Jmeter 不断压测发现，最初最小请求耗时是正常的：

<img width="871" alt="image" src="https://user-images.githubusercontent.com/77398366/204086853-397a2b26-fb70-463c-b74d-8961b58268e8.png">

后期会出现 Integer 最大值：

<img width="856" alt="image" src="https://user-images.githubusercontent.com/77398366/204086879-bf189414-2aad-4965-a97e-3d9c43bad871.png">

**Comment by iwangjie** [comment]
遇到了同样的问题，为何关闭呢？ @wujiuye

**Comment by magestacks** [comment]
我看大佬已修复，期待下个版本～

**Comment by wujiuye** [comment]
[1.1.3-RELEASE](https://github.com/wujiuye/qps-helper/releases/tag/1.1.3-RELEASE)

**Comment by magestacks** [comment]
收到
